import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({ weight: "600", style: "normal", subsets: ["latin"] });

export const metadata = {
  title: "Oalah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-color-accent scrollbar-w-12
         scrollbar-thumb-bg-gray-700 scrollbar-thumb-rounded-full scrollbar-track-bg-gray-300`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
